image: maven:3.6.1-jdk-11

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

before_script:
  - . setup-mvn-proxy.sh

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn compile
    - mvn package

test java:
  stage: test
  script:
    - mvn compile && mvn test --batch-mode

deploy:
  stage: deploy
  before_script:
    - . setup-mvn-proxy.sh
    - chmod 400 $CI_SSH_KEY
  dependencies:
    - test java
  script:
    - mvn compile
    - mvn package
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY target/server.war gitlabci@192.168.75.28:/opt/tomcat/webapps/v2.war
