image: maven:3.6.1-jdk-11

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

before_script:
  - . setup-mvn-proxy.sh

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - cd server/
    - mvn compile
    - mvn package

test java:
  stage: test
  script:
    - cd server/
    - mvn compile && mvn test --batch-mode

deploy:
  stage: deploy
  before_script:
    - . setup-mvn-proxy.sh
    - chmod 400 $CI_SSH_KEY
  dependencies:
    - test java
  script:
    - cd frontend/
    - mvn package
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY target/TP-Client-AJAX.war gitlabci@192.168.75.28:/opt/tomcat/webapps/client.war
    - cd src/main/
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY webapp/css/main.css gitlabci@192.168.75.28:/var/www/client/css/main.css
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY webapp/js/main.css gitlabci@192.168.75.28:/var/www/client/js/scripts.js
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY webapp/index.html gitlabci@192.168.75.28:/var/www/client/index.html
